import { z } from "zod";

const path = z.string().min(1).max(4096).describe("Workspace-relative path");
const position = z.object({ path, line: z.number().int().positive(), column: z.number().int().positive() }).strict();
const qualified = z.object({ qualifiedName: z.string().min(1).max(1000) }).strict();
export const target = z.xor([position, qualified]);
export const range = z.object({ line: z.number().int().positive(), column: z.number().int().positive(), endLine: z.number().int().positive(), endColumn: z.number().int().positive() }).strict().superRefine((value, context) => {
  if (value.endLine < value.line || value.endLine === value.line && value.endColumn < value.column) context.addIssue({ code: "custom", message: "range end must not precede range start" });
});
const cursor = z.union([z.string().max(4096), z.null()]).optional().transform(value => value ?? undefined);
const page = { limit: z.number().int().min(1).max(200).default(50), cursor, includeTotal: z.boolean().default(false) };
const symbolKinds = z.enum(["file", "module", "namespace", "package", "class", "method", "property", "field", "constructor", "enum", "interface", "function", "variable", "constant", "enumMember", "struct", "event", "operator", "typeParameter"]);
const visibility = z.enum(["public", "protected", "package", "private"]);
const namePattern = z.string().max(200).optional();
const testSelector = z.object({ path, className: z.string().min(1).max(1000).optional(), methodName: z.string().min(1).max(1000).optional() }).strict();
const coverageOptions = z.object({ enabled: z.boolean().default(true), includes: z.array(z.string().min(1).max(1000)).max(100).default([]), details: z.enum(["summary", "files"]).default("files"), limit: z.number().int().min(1).max(200).default(50), cursor, includeTotal: z.boolean().default(false) }).strict();
export const inputs = {
  java_status: z.object({ waitForReady: z.boolean().default(false), timeoutMs: z.number().int().min(1).max(600_000).default(120_000) }).strict(),
  java_outline: z.object({ path, depth: z.number().int().min(0).max(20).default(2), visibility: z.array(visibility).min(1).max(4).default(["public", "protected", "package", "private"]), kinds: z.array(symbolKinds).min(1).max(20).default(["class", "interface", "enum", "constructor", "method", "field"]), format: z.literal("compact").default("compact"), containingLine: z.number().int().positive().optional(), ...page, namePattern }).strict(),
  java_search_symbols: z.object({ query: z.string().min(1).max(500), kinds: z.array(symbolKinds).max(20).optional(), scope: z.enum(["workspace", "dependencies", "all"]).default("workspace"), mode: z.enum(["exact", "prefix", "camelCase", "fuzzy"]).default("fuzzy"), includeImplementation: z.boolean().default(false), ...page }).strict(),
  java_find_definition: z.object({ target, expand: z.array(z.enum(["context", "body", "members"])).max(3).default([]), contextLines: z.number().int().min(0).max(50).default(10), maxSourceCharacters: z.number().int().min(100).max(50_000).default(4000), includeDocumentation: z.boolean().default(false), maxDocumentationCharacters: z.number().int().min(0).max(10_000).default(1000), ...page }).strict(),
  java_find_references: z.object({ target, includeDeclaration: z.boolean().default(false), scope: z.enum(["workspace", "all"]).default("workspace"), usageKinds: z.array(z.enum(["call", "read", "write"])).min(1).max(3).optional(), within: target.optional(), includeEnclosing: z.boolean().default(false), includeText: z.boolean().default(false), contextLines: z.number().int().min(0).max(20).default(0), maxSnippetCharacters: z.number().int().min(100).max(10_000).default(1000), ...page }).strict(),
  java_call_hierarchy: z.object({ target, direction: z.enum(["incoming", "outgoing"]), callerScope: z.enum(["production", "tests", "all"]).default("production").describe("Incoming callers to return; ignored for outgoing hierarchies"), depth: z.number().int().min(1).max(3).default(1), limitPerNode: z.number().int().min(1).max(200).default(25), ...page }).strict(),
  java_type_hierarchy: z.object({ target, direction: z.enum(["supertypes", "subtypes", "both"]).default("both"), depth: z.number().int().min(1).max(3).default(2), ...page }).strict(),
  java_diagnostics: z.object({ scope: z.enum(["path", "paths", "workspace"]), path: path.optional(), paths: z.array(path).max(200).optional(), minimumSeverity: z.enum(["error", "warning", "info", "hint"]).default("warning"), waitForCurrentVersion: z.boolean().default(true), includeText: z.boolean().default(false), timeoutMs: z.number().int().min(1).max(120_000).default(30_000), ...page }).strict().superRefine((v, ctx) => {
    if (v.scope === "path" && !v.path) ctx.addIssue({ code: "custom", message: "path is required for path scope" });
    if (v.scope === "paths" && !v.paths?.length) ctx.addIssue({ code: "custom", message: "paths is required for paths scope" });
    if (v.scope !== "path" && v.path) ctx.addIssue({ code: "custom", message: "path is only valid for path scope" });
    if (v.scope !== "paths" && v.paths) ctx.addIssue({ code: "custom", message: "paths is only valid for paths scope" });
  }),
  java_compile: z.object({ kind: z.enum(["incremental", "clean"]).default("incremental"), minimumSeverity: z.enum(["error", "warning", "info", "hint"]).default("warning"), includeText: z.boolean().default(false), timeoutMs: z.number().int().min(1).max(600_000).default(120_000), ...page }).strict(),
  java_run_tests: z.object({ path: path.optional(), className: z.string().min(1).max(1000).optional(), methodName: z.string().min(1).max(1000).optional(), tests: z.array(testSelector).min(1).max(100).optional(), compile: z.enum(["incremental", "clean", "none"]).default("incremental"), compileProjectOnly: z.boolean().default(false), workingDirectory: path.optional(), vmArgs: z.array(z.string().max(2000)).max(50).default([]), systemProperties: z.record(z.string().max(500), z.string().max(4000)).default({}), timeoutMs: z.number().int().min(1).max(600_000).default(120_000), includeOutput: z.boolean().default(false), includeStackTrace: z.boolean().default(false), debug: z.boolean().default(false), coverage: coverageOptions.optional(), ...page }).strict().superRefine((value, ctx) => { if (!value.path && !value.tests) ctx.addIssue({ code: "custom", message: "path or tests is required" }); if (value.path && value.tests) ctx.addIssue({ code: "custom", message: "path and tests are mutually exclusive" }); if (!value.path && (value.className || value.methodName)) ctx.addIssue({ code: "custom", message: "top-level className and methodName require path" }); }),
  java_find_affected_tests: z.object({ target, transitive: z.boolean().default(true), maxDepth: z.number().int().min(1).max(20).default(10), timeoutMs: z.number().int().min(1).max(600_000).default(120_000), ...page }).strict(),
  java_find_unused_code: z.object({ path: path.optional(), kinds: z.array(z.enum(["method", "constructor", "field"])).min(1).max(3).default(["method", "constructor", "field"]), includeWriteOnly: z.boolean().default(true), timeoutMs: z.number().int().min(1).max(600_000).default(120_000), ...page }).strict(),
  java_code_actions: z.object({ path, range, diagnosticCodes: z.array(z.union([z.string(), z.number()])).max(100).default([]), kinds: z.array(z.string()).max(20).default(["quickfix"]), ...page }).strict(),
  java_edit_preview: z.discriminatedUnion("operation", [
    z.object({ operation: z.literal("rename"), target, newName: z.string().min(1).max(500), includeDiff: z.boolean().default(false), ...page }).strict(),
    z.object({ operation: z.literal("codeAction"), id: z.string().min(1), includeDiff: z.boolean().default(false), ...page }).strict(),
    z.object({ operation: z.literal("organizeImports"), path, includeDiff: z.boolean().default(false), ...page }).strict(),
    z.object({ operation: z.literal("format"), path, range: range.optional(), includeDiff: z.boolean().default(false), ...page }).strict(),
  ]),
  java_debug_targets: z.object({ query: z.string().max(500).optional(), includeUnavailable: z.boolean().default(false) }).strict(),
  java_debug_attach: z.object({ targetId: z.string().min(1).max(200), timeoutMs: z.number().int().min(1).max(60_000).default(10_000) }).strict(),
  java_debug_sessions: z.object({}).strict(),
  java_debug_set_breakpoints: z.object({ sessionId: z.string().min(1).max(200), sourcePath: path, breakpoints: z.array(z.object({ line: z.number().int().positive() }).strict()).max(200), timeoutMs: z.number().int().min(1).max(60_000).default(5_000) }).strict(),
  java_debug_threads: z.object({ sessionId: z.string().min(1).max(200), includeSystemThreads: z.boolean().default(false) }).strict(),
  java_debug_wait_for_stop: z.object({ sessionId: z.string().min(1).max(200), timeoutMs: z.number().int().min(1).max(60_000).default(30_000) }).strict(),
  java_debug_stack_trace: z.object({ sessionId: z.string().min(1).max(200), stopId: z.string().min(1).max(200), threadId: z.number().int().nonnegative(), startFrame: z.number().int().nonnegative().default(0), maxFrames: z.number().int().min(1).max(100).default(20) }).strict(),
  java_debug_variables: z.object({ sessionId: z.string().min(1).max(200), stopId: z.string().min(1).max(200), frameId: z.string().min(1).max(300).optional(), valueId: z.string().min(1).max(300).optional(), scope: z.enum(["arguments", "locals", "this", "all"]).default("all"), start: z.number().int().nonnegative().default(0), limit: z.number().int().min(1).max(200).default(50) }).strict().superRefine((value, context) => { if (Boolean(value.frameId) === Boolean(value.valueId)) context.addIssue({ code: "custom", message: "exactly one of frameId or valueId is required" }); }),
  java_debug_execute: z.object({ sessionId: z.string().min(1).max(200), action: z.enum(["continue", "step_over", "step_into", "step_out"]), threadId: z.number().int().nonnegative().optional(), stopId: z.string().min(1).max(200).optional(), waitTimeoutMs: z.number().int().min(0).max(60_000).default(0) }).strict().superRefine((value, context) => { if (value.action !== "continue" && (value.threadId === undefined || !value.stopId)) context.addIssue({ code: "custom", message: "step actions require threadId and stopId" }); }),
  java_debug_detach: z.object({ sessionId: z.string().min(1).max(200) }).strict(),
  java_debug_hot_swap: z.object({ sessionId: z.string().min(1).max(200), sourcePaths: z.array(path).min(1).max(200), dryRun: z.boolean().default(false) }).strict(),
} as const;

const anyObject = z.object({}).catchall(z.unknown());
const debugLocation = z.object({ className: z.string(), methodName: z.string(), sourcePath: z.string().optional(), line: z.number().int().positive().optional() }).strict();
const debugTarget = z.object({ targetId: z.string(), pid: z.number().int().nonnegative(), displayName: z.string(), command: z.string().optional(), jdwp: z.object({ status: z.enum(["enabled", "not_enabled", "unknown"]), transport: z.string().optional(), server: z.boolean().optional(), suspend: z.boolean().optional(), address: z.string().optional() }).strict(), attachable: z.union([z.boolean(), z.literal("unknown")]), unavailableReason: z.string().optional() }).strict();
const debugCapabilities = z.object({ canRedefineClasses: z.boolean(), canPopFrames: z.boolean(), canGetBytecodes: z.boolean(), canGetSyntheticAttribute: z.boolean(), canWatchFieldAccess: z.boolean(), canWatchFieldModification: z.boolean() }).strict();
const debugSession = z.object({ sessionId: z.string(), targetId: z.string(), pid: z.number().int().nonnegative(), vmName: z.string(), vmVersion: z.string(), state: z.enum(["running", "stopped"]), attachedAt: z.string(), capabilities: debugCapabilities }).strict();
const debugStopped = z.object({ outcome: z.literal("stopped"), stopId: z.string(), reason: z.enum(["breakpoint", "step", "exception", "pause"]), threadId: z.number().int().nonnegative(), location: debugLocation, breakpointId: z.string().optional() }).strict();
const debugWait = z.union([debugStopped, z.object({ outcome: z.literal("timeout"), state: z.enum(["running", "stopped"]) }).strict(), z.object({ outcome: z.enum(["terminated", "disconnected"]) }).strict()]);
export const outputs = {
  java_status: z.object({ state: z.string(), ready: z.boolean(), activity: z.string().optional(), projectKind: z.string(), modules: z.number(), compiler: z.literal("ecj"), mcpRevision: z.string(), jdtVersion: z.string(), toolingJdk: z.string(), projectJdk: z.string(), sourceEncoding: z.string().optional(), excludedProjects: z.array(z.string()).optional(), testClasspathEntries: z.array(z.string()).optional(), trusted: z.boolean(), offline: z.boolean(), message: z.string().optional(), problems: z.array(z.string()).optional() }).strict(),
  java_outline: z.object({ symbols: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_search_symbols: z.object({ symbols: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional(), warnings: z.array(anyObject).optional() }).strict(),
  java_find_definition: z.object({ definitions: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional(), documentation: z.string().optional() }).strict(),
  java_find_references: z.object({ references: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_call_hierarchy: z.object({ root: anyObject, nodes: z.array(anyObject), edges: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_type_hierarchy: z.object({ root: anyObject, nodes: z.array(anyObject), edges: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_diagnostics: z.object({ status: z.enum(["final", "partial"]), diagnostics: z.array(anyObject), counts: anyObject, pendingPaths: z.array(z.string()).optional(), message: z.string().optional(), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_compile: z.object({ kind: z.string(), buildStatus: z.enum(["failed", "succeeded", "with-errors", "cancelled", "unknown"]), excludedProjects: z.array(z.string()).optional(), durationMs: z.number(), complete: z.boolean(), success: z.boolean(), diagnosticsComplete: z.boolean(), counts: anyObject, diagnostics: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional(), message: z.string().optional(), buildFailures: z.array(z.string()).optional() }).strict(),
  java_run_tests: z.union([z.object({ status: z.enum(["passed", "failed", "compile-failed", "error", "timed-out"]), durationMs: z.number(), counts: anyObject, failures: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional(), message: z.string().optional(), output: anyObject.optional(), coverage: anyObject.optional() }).strict(), z.object({ status: z.literal("debugging"), debugSessions: z.array(z.object({ sessionId: z.string(), targetId: z.string(), pid: z.number().int().nonnegative(), selectors: z.array(z.string()) }).strict()) }).strict()]),
  java_find_affected_tests: z.object({ tests: z.array(anyObject), complete: z.boolean(), total: z.number().optional(), nextCursor: z.string().optional(), message: z.string().optional() }).strict(),
  java_find_unused_code: z.object({ candidates: z.array(anyObject), complete: z.boolean(), total: z.number().optional(), nextCursor: z.string().optional(), message: z.string().optional() }).strict(),
  java_code_actions: z.object({ actions: z.array(anyObject), total: z.number().optional(), nextCursor: z.string().optional() }).strict(),
  java_edit_preview: z.object({ files: z.array(anyObject), total: z.number().optional(), editCount: z.number(), nextCursor: z.string().optional(), unifiedDiff: z.string().optional() }).strict(),
  java_debug_targets: z.object({ targets: z.array(debugTarget) }).strict(),
  java_debug_attach: z.object({ session: debugSession }).strict(),
  java_debug_sessions: z.object({ sessions: z.array(z.object({ sessionId: z.string(), targetId: z.string(), pid: z.number().int().nonnegative(), displayName: z.string(), state: z.enum(["running", "stopped", "disconnected", "terminated"]), stopId: z.string().optional(), stoppedThreads: z.array(z.number().int().nonnegative()) }).strict()) }).strict(),
  java_debug_set_breakpoints: z.object({ sourcePath: z.string(), breakpoints: z.array(z.object({ breakpointId: z.string(), requestedLine: z.number().int().positive(), resolvedLine: z.number().int().positive().optional(), className: z.string().optional(), state: z.enum(["verified", "pending", "rejected"]), message: z.string().optional() }).strict()) }).strict(),
  java_debug_threads: z.object({ threads: z.array(z.object({ threadId: z.number().int().nonnegative(), name: z.string(), status: z.string(), suspended: z.boolean(), stopReason: z.enum(["breakpoint", "step", "exception", "pause"]).optional(), location: debugLocation.optional() }).strict()) }).strict(),
  java_debug_wait_for_stop: debugWait,
  java_debug_stack_trace: z.object({ totalFrames: z.number().int().nonnegative(), frames: z.array(z.object({ frameId: z.string(), index: z.number().int().nonnegative(), className: z.string(), methodName: z.string(), methodSignature: z.string().optional(), sourcePath: z.string().optional(), line: z.number().int().positive().optional(), native: z.boolean() }).strict()) }).strict(),
  java_debug_variables: z.object({ variables: z.array(z.object({ name: z.string(), declaredType: z.string().optional(), runtimeType: z.string().optional(), value: z.string(), kind: z.enum(["null", "primitive", "string", "object", "array", "class"]), valueId: z.string().optional(), childCount: z.number().int().nonnegative().optional() }).strict()), total: z.number().int().nonnegative().optional() }).strict(),
  java_debug_execute: z.union([debugWait, z.object({ outcome: z.literal("running") }).strict()]),
  java_debug_detach: z.object({ detached: z.boolean(), targetState: z.string() }).strict(),
  java_debug_hot_swap: z.object({ outcome: z.enum(["applied", "validated", "no_changes", "compile_failed", "redefine_failed"]), classes: z.array(z.object({ className: z.string(), sourcePath: z.string().optional(), status: z.enum(["applied", "validated", "not_loaded", "unsupported_change", "compile_error", "redefine_error"]), message: z.string().optional() }).strict()), diagnostics: z.array(z.object({ sourcePath: z.string().optional(), line: z.number().int().positive().optional(), column: z.number().int().positive().optional(), severity: z.enum(["error", "warning"]), message: z.string() }).strict()), breakpoints: z.object({ restored: z.array(z.string()), pending: z.array(z.string()), rejected: z.array(z.string()) }).strict(), activeFrames: z.array(z.object({ threadId: z.number().int().nonnegative(), frameId: z.string().optional(), className: z.string(), methodName: z.string(), obsolete: z.boolean() }).strict()) }).strict(),
} as const;
export type ToolName = keyof typeof inputs;
